import os

from .helper import fix_assets_path

STATIC_ASSETS_PATH = fix_assets_path(os.environ.get("EVENT_FIXED_ASSET_PATH", "../client/build"))
EVENT_ASSET_MEDIA_FOLDER = os.environ.get("EVENT_ASSET_MEDIA_FOLDER", fix_assets_path("../dynamic_asset"))
EVENT_FLASK_SERVER = os.environ.get("FLASK_SERVER_NAME", None)
EVENT_MYSQL_DATABASE_HOST = os.environ.get("EVENT_MYSQL_DATABASE_HOST", "localhost")
EVENT_MYSQL_DATABASE_PORT = os.environ.get("EVENT_MYSQL_DATABASE_PORT", 3306)
EVENT_MYSQL_DATABASE_NAME = os.environ.get("EVENT_MYSQL_DATABASE_NAME", "")
EVENT_MYSQL_DATABASE_USER = os.environ.get("EVENT_MYSQL_DATABASE_USER", "")
EVENT_MYSQL_DATABASE_PASSWORD = os.environ.get("EVENT_MYSQL_DATABASE_PASSWORD", "")
EVENT_MYSQL_DATABASE_CHARSET = os.environ.get("EVENT_MYSQL_DATABASE_", "utf8")
EVENT_MYSQL_DATABASE_SSL_VERIFY_CERT = os.environ.get("EVENT_MYSQL_DATABASE_SSL_VERIFY_CERT", False)
EVENT_MYSQL_DATABASE_SSL_CA_PATH = os.environ.get("EVENT_MYSQL_DATABASE_SSL_CA_PATH", "")
EVENT_MYSQL_DATABASE_POOL_RESET_SESSION = os.environ.get("EVENT_MYSQL_DATABASE_POOL_RESET_SESSION", True)
EVENT_MYSQL_DATABASE_POOL_SIZE = int(os.environ.get("EVENT_MYSQL_DATABASE_POOL_SIZE", 10))
